apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec:
      version: "5.6.14"
  test:
    enable: false
  values:
    controller:
      replicaCount: 2
      publishService:
        enabled: true
      service:
        externalTrafficPolicy: Local
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    defaultBackend:
      enabled: true
      nodeSelector:
        beta.kubernetes.io/os: linux

  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
